apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  ##deployment labels
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  ReplicaSet: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: payment
      tier: app
      
# This is pod definition
  template:
    metadata:
      project: roboshop
      component: payment
      tier: app
    spec:
      containers:
        - name: payment
          image: saitejarageti/payment:v1
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  selector:
    project: roboshop
    component: payment
    tier: app
    
  ports:
    - protocol: TCP
      port: 8080 ##serviceport
      targetPort: 8080 ##containerport

