apiVersion: v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  ##deployment labels
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  ReplicaSet: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
      
# This is pod definition
  template:
    metadata:
      project: roboshop
      component: mongodb
      tier: database
    spec:
      containers:
        - name: mongodb
          image: saitejarageti/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: database
    
  ports:
    - protocol: TCP
      port: 27017 ##serviceport
      targetPort: 27017 ##containerport

