apiVersion: v1
kind: secret
metadata:
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
type: opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  ##deployment labels
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  ReplicaSet: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
      
# This is pod definition
  template:
    metadata:
      project: roboshop
      component: mysql
      tier: database
    spec:
      containers:
        - name: mysql
          image: saitejarageti/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  selector:
    project: roboshop
    component: mysql
    tier: database
    
  ports:
    - protocol: TCP
      port: 3306 ##serviceport
      targetPort: 3306 ##containerport