apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v2
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  ##deployment labels
  labels:
    project: roboshop
    component: catalogue
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: app
      
# This is pod definition
  template:
    metadata:
      project: roboshop
      component: catalogue
      tier: app
    spec:
      containers:
        - name: catalogue
          image: saitejarageti/catalogue:v1
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: app
    
  ports:
    - protocol: TCP
      port: 8080 ##serviceport
      targetPort: 8080 ##containerport

