apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
  MONGO: "true"
---
apiVersion: v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  ##deployment labels
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  ReplicaSet: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: app
      
# This is pod definition
  template:
    metadata:
      project: roboshop
      component: user
      tier: app
    spec:
      containers:
        - name: user
          image: saitejarageti/user:v1
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  selector:
    project: roboshop
    component: user
    tier: app
    
  ports:
    - protocol: TCP
      port: 8080 ##serviceport
      targetPort: 8080 ##containerport

